name: CI

run-name: >-
  ${{ github.event_name == 'pull_request'
  && format('CI · PR #{0} · {1} · @{2}', github.event.pull_request.number, github.event.pull_request.head.ref, github.actor)
  || format('CI · push {0} · @{1}', github.ref_name, github.actor) }}

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  check:
    name: macOS / make check
    if: github.repository == 'apple/coreai-optimization'
    runs-on: [self-hosted, macos, tahoe, ARM64]
    timeout-minutes: 30
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false
      - name: Run `make check`
        run: make check

  macos-tests:
    name: macOS / make test-highest-pytorch / markers=not-slow
    needs: [check]
    if: github.repository == 'apple/coreai-optimization'
    runs-on: [self-hosted, macos, tahoe, ARM64]
    timeout-minutes: 60
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false
      - name: Run `make test-highest-pytorch`
        run: make test-highest-pytorch PYTEST_ARGS="--marker 'not slow' --junit"
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results-macos-highest-fast
          path: test-results/
